### ISSUE TITLE
Spew of errors with particle decelerator

### ISSUE THREAD

**Issue by Jimmy469** [Lach01298/QMD#56] opened 2021-07-11 00:33 UTC
As seen here: https://youtu.be/vFdj829eOdA?t=2145

Accompanying crash report: https://paste.dimdev.org/evumizotis.mccrash (just one of many, but they all look similar)

Let me know if additional information is needed (decelerator design, etc.)

**Comment by Lach01298** [comment] 2021-07-11 02:13
I think this and the other bug are caused by the multiblock not forgetting its particle beams after being broken

**Comment by Lach01298** [comment] 2021-08-01 03:39
Fixed in 1.0.0-beta

**Closed by Lach01298** 2021-08-01 03:39 UTC
Labels: bug
