### ISSUE TITLE
JEI crashes

### ISSUE THREAD

**Issue by marcin212** [Lach01298/QMD#9] opened 2020-05-04 17:27 UTC
When I add QMD to my modpack, JEI crashes.
Exception and mod list in the logs.
logs: https://pastebin.com/Uw4Q4xQ7
QMD: 0.6.2-1.12.2

**Comment by Lach01298** [comment] 2020-05-07 06:16
Strange I can't reproduce that with the same versions of QMD and JEI. It must be some strange 3rd party interaction? Does it happen with just JEI, QMD and NC? If not I think this is a bug for JEI not QMD.

**Comment by marcin212** [comment] 2020-05-07 14:16
It doesn't  happen with just JEI, QMD and NC.

**Comment by Lach01298** [comment] 2020-05-08 06:17
I wonder what mod interferes. I can't think of anything I'm doing with JEI colours.

**Comment by marcin212** [comment] 2020-05-10 17:23
I found reproduce.
1. Mod list:
- jei_1.12.2-4.15.0.291
- NuclearCraft-2o.2.6-1.12.2
- QMD-0.6.2-1.12.2
-  forge-14.23.5.2854
2. Set `colorSearchMode` to `require_prefix` in `config/jei/jei.cfg`
3. Run minecraft. 
4. Minecraft should crash
5. Remove QMD
6. Run Minecraft
7. Minecraft should works fine

**Comment by DarkAmbientNoise** [comment] 2020-06-07 05:04
I second the above reproduction (nice job on finding that), having any color search enabled in JEI for some strange reason, causes a loading crash. Disabling it, allows it to load.

Base Setup:
MC: 1.12.2
F: 14.23.5.2854

Mods: 3
JEI: 4.15.0.291
Nuclear Craft Overhauled: 2o2.7
QMD: 0.7a

Config Settings:
JEI: S:colorSearchMode=Enabled

Is the mod automatically generating materials from other mods materials? If so there could be something wrong with the hook that tries to pull colors from those materials. I'm not a modder, I just see tons of crash reports and try to learn from them, nothing but a weak suggestion.

**Comment by Lach01298** [comment] 2020-06-27 04:46
Fixed in 0.8.0

**Closed by Lach01298** 2020-06-27 04:46 UTC
Labels: bug
